name: Production

on:
  push:
    branches: [master]

jobs:
  devlopment:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      USERNAME: ${{ secrets.USERNAME }}
      PORT: ${{ secrets.PORT }}
      KEY: ${{ secrets.SSHKEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Copy file via scp
        uses: appleboy/scp-action@master
        with:
          source: "."
          target: "cdtoken_fe"

      - name: Executing remote  command
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd cdtoken_fe
            git pull origin master
            git status
            npm install
            npm run build
